name: Build exe

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          architecture: 'x64'

      - name: Install dep
        run: |
          npm install && npm install -g pkg

      - name: Bundle js
        run: |
          npm run build

      - name: Build exe
        run: |
          pkg -t node18-win heic-converter.js

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: heic-converter.exe
          asset_name: heic-converter-win64.exe
          tag: ${{ github.ref }}
          overwrite: true
          release_name: "Build file"